### ISSUE TITLE
Disable wasm on firefox

### ISSUE THREAD

**Issue by tudor-phd** [MaxGraey/wasm-check#3]
Hi,

**Issue description:**

If I go on Firefox and open about:config ; search for javascript.options.wasm and set it to false, the package will throw an error

**Steps to reproduce the issue:**
1. Open Firefox
2. Open about:config
3. Search by javascript.options.wasm
4. Set the value to false
5. Open an app where you added wasm-check package

**What's the expected result?**
Catch the case when the wasm is disabled.

**What's the actual result?**
App crashes with error: Uncaught ReferenceError: WebAssembly is not defined

**Additional details / screenshot:**
<img width="1433" alt="Screenshot 2021-03-29 at 12 07 03" src="https://user-images.githubusercontent.com/18324739/112991009-58ac0d00-916f-11eb-86fe-cd9f1dca492a.png">
<img width="1430" alt="Screenshot 2021-03-30 at 15 47 38" src="https://user-images.githubusercontent.com/18324739/112991014-5b0e6700-916f-11eb-8498-d10dcfc5a0a2.png">

**Comment by MaxGraey** [comment]
Oh, what? I didn't know browser can disable WebAssembly completely!
Thanks for report!

**Comment by michalsnik** [comment]
On 2.0.3 I'm still getting this error @MaxGraey

To reproduce you can follow steps from the original issue and visit this codesandbox:
https://codesandbox.io/s/hardcore-star-20fy3h?file=/src/index.js

Preview:
![image](https://user-images.githubusercontent.com/4093559/161598669-ef1ff8ee-75d9-4063-89b5-085ba75b68e6.png)
